/*
 Sliding Paypal Shopping Cart
 Version: 1.0.5
 (c) 2014 DMXzone.com
 @build 01-04-2014 14:18:38
*/
(function(g){function q(a,c){if(!a)return"";for(var f=PAYPAL.apps.MiniCart.products,g=PAYPAL.apps.MiniCart.calculateSubtotal(),k=0,m=0;m<f.length;m++)""!==f[m].product.item_name&&k++;c&&c.product&&(a=a.replace(/##current_product_price##/gi,c.product.amount).replace(/##current_product_name##/gi,c.product.item_name).replace(/##current_product_quantity##/gi,c.product.quantity));return a.replace(/##foreach_product##(.*?)##end_foreach_product##/gi,function(a,c){for(var d="",e=0;e<f.length;e++)var b=f[e].product,
d=d+c.replace(/##product_price##/gi,b.amount).replace(/##product_name##/gi,b.item_name).replace(/##product_quantity##/gi,b.quantity);return d}).replace(/##total_products##/gi,k).replace(/##subtotal##/gi,g)}function k(){var a="/Styles/dmxSlidingCart/",c=g('link[href*="dmxSlidingCart/"]');0<c.length&&(a=c[0].href,a=a.substring(0,a.lastIndexOf("/"))+"/");return a}var a={design:"light-default",parent:"body",strings:{button:"Checkout",subtotal:"Subtotal: ",discount:"Discount: ",shipping:"does not include shipping &amp; tax",
processing:"Processing..."},paypalURL:"https://www.paypal.com/cgi-bin/webscr",name:"dmxSPSCart",cartDuration:20,assetURL:"/Styles/dmxSlidingCart/"},c={};g.dmxSlidingCart=function(d){var e=g.extend(!0,{},a,d);e.assetURL=k();"number"==typeof e.edgeDistance&&(e.edgeDistance+="px");"body"===e.parent&&(e.parent=document.body);e.string&&(e.string.subtotal&&" "!=e.string.subtotal.slice(-1)&&(e.string.subtotal+=" "),e.string.discount&&" "!=e.string.discount.slice(-1)&&(e.string.discount+=" "));e.events&&
g.each("onRender afterRender onHide afterHide onShow afterShow onAddToCart afterAddToCart onRemoveFromCart afterRemoveFromCart onCheckout onReset afterReset".split(" "),function(a,c){if("string"==typeof e.events[c]){var d=e.events[c];e.events[c]=function(a){(new Function(q(d,a))).call();if(null!==document.MM_returnValue)return document.MM_returnValue}}});c=e;PAYPAL.apps.MiniCart.render(e)};g.dmxSlidingCart.addToCart=function(a){a.business=c.business;a.currency_code=c.currency;a["return"]=c.returnUrl;
a.cancel_return=c.cancelUrl;for(var e=0;10>e;e++)if(a["os"+e]){var f=g(':input[name="'+a["os"+e]+'"]');if(f.is(":checkbox")||f.is(":radio"))f=f.filter(":checked");f=f.val()||"";a["os"+e]=g.isArray(f)?f.join(","):f}PAYPAL.apps.MiniCart.addToCart(a);if(e=window.event||arguments.callee.caller.arguments[0])e=jQuery.Event(e),e.preventDefault()};g.dmxSlidingCart.toggle=function(){PAYPAL.apps.MiniCart.toggle()};g.dmxSlidingCart.show=function(){PAYPAL.apps.MiniCart.show()};g.dmxSlidingCart.hide=function(){PAYPAL.apps.MiniCart.hide()};
g.dmxSlidingCart.reset=function(){PAYPAL.apps.MiniCart.reset()};g.dmxSlidingCart.updateSubtotal=function(){PAYPAL.apps.MiniCart.updateSubtotal()}})(jQuery);if("undefined"===typeof PAYPAL||!PAYPAL)var PAYPAL={};PAYPAL.apps=PAYPAL.apps||{};
(function(){var g={parent:document.body,displayEdge:"right",edgeDistance:"50px",formTarget:null,cookiePath:"/",cartDuration:30,strings:{button:"Checkout",subtotal:"Subtotal: ",discount:"Discount: ",shipping:"does not include shipping & tax",processing:"Processing..."},name:"PPMiniCart",peekEnabled:!0,paypalURL:"https://www.paypal.com/cgi-bin/webscr",assetURL:"http://www.minicartjs.com/build/",events:{onRender:null,afterRender:null,onHide:null,afterHide:null,onShow:null,afterShow:null,onAddToCart:null,
afterAddToCart:null,onRemoveFromCart:null,afterRemoveFromCart:null,onCheckout:null,onReset:null,afterReset:null}};if(!PAYPAL.apps.MiniCart){PAYPAL.apps.MiniCart=function(){var a={},c=!1,d=!1,e={_cart:!0,_xclick:!0},f=/^(?:business|currency_code|lc|paymentaction|no_shipping|cn|no_note|invoice|handling_cart|weight_cart|weight_unit|tax_cart|page_style|image_url|cpp_|cs|cbt|return|cancel_return|notify_url|rm|custom|charset)/,l=function(){var b=g.name,a=[];a.push("#"+b+" form { position:fixed; float:none; top:-250px; "+
g.displayEdge+":"+g.edgeDistance+"; width:265px; margin:0; padding:50px 10px 0; min-height:170px; background:#fff url("+g.assetURL+"images/minicart_sprite.png) no-repeat -125px -60px; border:1px solid #999; border-top:0; font:13px/normal arial, helvetica; color:#333; text-align:left; -moz-border-radius:0 0 8px 8px; -webkit-border-radius:0 0 8px 8px; border-radius:0 0 8px 8px; -moz-box-shadow:1px 1px 1px rgba(0, 0, 0, 0.1); -webkit-box-shadow:1px 1px 1px rgba(0, 0, 0, 0.1); box-shadow:1px 1px 1px rgba(0, 0, 0, 0.1); } ");
a.push("#"+b+" ul { position:relative; overflow-x:hidden; overflow-y:auto; height:130px; margin:0 0 7px; padding:0; list-style-type:none; border-top:1px solid #ccc; border-bottom:1px solid #ccc; } ");a.push("#"+b+" li { position:relative; margin:-1px 0 0; padding:6px 5px 6px 0; border-top:1px solid #f2f2f2; } ");a.push("#"+b+" li a { display: block; width: 155px; color:#333; text-decoration:none; white-space:nowrap; overflow:hidden; text-overflow:ellipsis; } ");a.push("#"+b+" li a span { display:block; color:#999; font-size:10px; } ");
a.push("#"+b+" li .quantity { position:absolute; top:.5em; right:78px; width:22px; padding:1px; border:1px solid #83a8cc; text-align:right; } ");a.push("#"+b+" li .price { position:absolute; top:.5em; right:4px; } ");a.push("#"+b+" li .remove { position:absolute; top:9px; right:60px; width:14px; height:14px; background:url("+g.assetURL+"images/minicart_sprite.png) no-repeat -134px -4px; border:0; cursor:pointer; } ");a.push("#"+b+" p { margin:0; padding:0 0 0 20px; background:url("+g.assetURL+"images/minicart_sprite.png) no-repeat; font-size:13px; font-weight:bold; } ");
a.push("#"+b+" p:hover { cursor:pointer; } ");a.push("#"+b+" p input { float:right; margin:4px 0 0; padding:1px 4px; text-decoration:none; font-weight:normal; color:#333; background:#ffa822 url("+g.assetURL+"images/minicart_sprite.png) repeat-x left center; border:1px solid #d5bd98; border-right-color:#935e0d; border-bottom-color:#935e0d; -moz-border-radius:2px; -webkit-border-radius:2px; border-radius:2px; } ");a.push("#"+b+" p .shipping { display:block; font-size:10px; font-weight:normal; color:#999; } ");
b=document.createElement("style");b.type="text/css";b.styleSheet?b.styleSheet.cssText=a.join(""):b.appendChild(document.createTextNode(a.join("")));document.getElementsByTagName("head")[0].appendChild(b)},h=function(){var b=a.UI,c,e,d;b.wrapper=document.createElement("div");b.wrapper.id=g.name;c=document.createElement("input");c.type="hidden";c.name="cmd";c.value="_cart";e=c.cloneNode(!1);e.name="upload";e.value="1";d=c.cloneNode(!1);d.name="bn";d.value="MiniCart_AddToCart_WPS_US";b.cart=document.createElement("form");
b.cart.method="post";b.cart.action=g.paypalURL;g.formTarget&&(b.cart.target=g.formTarget);b.cart.appendChild(c);b.cart.appendChild(e);b.cart.appendChild(d);b.wrapper.appendChild(b.cart);b.itemList=document.createElement("ul");b.cart.appendChild(b.itemList);b.summary=document.createElement("p");b.cart.appendChild(b.summary);b.button=document.createElement("input");b.button.type="submit";b.button.value=g.strings.button;b.summary.appendChild(b.button);b.subtotal=document.createElement("span");k.util.setText(b.subtotal,
g.strings.subtotal);b.subtotalAmount=document.createElement("span");k.util.setText(b.subtotalAmount,"0.00");b.subtotal.appendChild(b.subtotalAmount);b.summary.appendChild(b.subtotal);b.shipping=document.createElement("span");b.shipping.className="shipping";k.util.setText(b.shipping,g.strings.shipping);b.summary.appendChild(b.shipping);window.attachEvent&&!window.opera&&(c=navigator.userAgent.match(/MSIE\s([^;]*)/))&&(c=parseFloat(c[1]),7>c||7<=c&&"BackCompat"===document.compatMode)&&(b.cart.style.position=
"absolute",b.wrapper.style[g.displayEdge]="0",b.wrapper.style.setExpression("top","x = document.documentElement.scrollTop ? document.documentElement.scrollTop : document.body.scrollTop"));("string"===typeof g.parent?document.getElementById(g.parent):g.parent).appendChild(b.wrapper)},m=function(){var b=a.UI,d,f,n;d=document.getElementsByTagName("form");for(n=0;n<d.length;n++)f=d[n],f.cmd&&e[f.cmd.value]&&a.bindForm(f);k.event.add(document,"click",function(d){if(c){d=d.target;var e=b.cart;if(!/input|button|select|option/i.test(d.tagName)){for(;1===
d.nodeType;){if(d===e)return;d=d.parentNode}a.hide(null)}}});k.event.add(b.cart,"submit",function(b){var c=g.events.onCheckout;"function"===typeof c&&!1===c.call(a,b)?b.preventDefault():a.UI.button.value=g.strings.processing});k.event.add(b.summary,"click",function(c){c.target!==b.button&&a.toggle(c)});k.event.add(window,"pageshow",function(b){b.persisted&&(s(!0),a.hide())});window.attachEvent&&!window.opera?k.event.add(document,"storage",function(a){setTimeout(s,100)}):k.event.add(window,"storage",
function(a){(a.key&&a.key===g.name||!a.key)&&s()})},x=function(a){for(var c in a)void 0!==typeof g[c]&&(g[c]=a[c])},s=function(b){a.products=[];k.util.setText(a.UI.itemList,"");k.util.setText(a.UI.subtotalAmount,"");a.UI.button.value=g.strings.button;var d,e,f;if(d=k.storage.load())for(e=d.length,f=0;f<e;f++)v(d[f])&&(c=!0);a.updateSubtotal(b)},v=function(b){var c=a.UI,d=c.cart,e=new q(b,a.UI.itemList.children.length+1),f=b.product.offset,g,h;a.products[f]=e;for(h in b.settings)d.elements[h]?d.elements[h].value?
d.elements[h].value=b.settings[h]:d.elements[h]=b.settings[h]:(g=document.createElement("input"),g.type="hidden",g.name=h,g.value=b.settings[h],d.appendChild(g));if(e.isPlaceholder)return!1;k.event.add(e.removeInput,"click",function(){w(e,f)});var l=e.quantityInput.value;k.event.add(e.quantityInput,"keyup",function(){var b=this;setTimeout(function(){var c=parseInt(b.value,10);isNaN(c)||c===l||(l=c,e.setQuantity(c),e.getQuantity()||w(e,f),a.updateSubtotal(),k.storage.save(a.products))},250)});c.itemList.insertBefore(e.liNode,
c.itemList.firstChild);k.util.animate(e.liNode,"opacity",{from:0,to:1});return!0},w=function(b,c){var d=g.events,e=d.onRemoveFromCart,f=d.afterRemoveFromCart;if("function"!==typeof e||!1!==e.call(a,b))b.setQuantity(0),b.quantityInput.style.display="none",k.util.animate(b.liNode,"opacity",{from:1,to:0},function(){k.util.animate(b.liNode,"height",{from:18,to:0},function(){try{b.liNode.parentNode.removeChild(b.liNode)}catch(c){}var d=a.UI.cart.getElementsByTagName("li"),e=d.length,g,k,u,h,t,n,l=1;for(t=
0;t<e;t++){g=d[t].getElementsByTagName("input");k=g.length;for(n=0;n<k;n++)u=g[n],(h=/(.+)_[0-9]+$/.exec(u.name))&&h[1]&&(u.name=h[1]+"_"+l);l++}"function"===typeof f&&f.call(a,b)})}),a.products[c].product.item_name="",a.products[c].product.item_number="",a.updateSubtotal(),k.storage.save(a.products,g.cartDuration)};a.products=[];a.UI={};a.render=function(b){var e;x(b);b=g.events;e=b.onRender;b=b.afterRender;if("function"!==typeof e||!1!==e.call(a))d||(l(),h(),m(),e=location.hash.substring(1),0===
e.indexOf(g.name+"=")&&(e=e.split("=")[1],"reset"===e&&(a.reset(),location.hash=""))),s(!0),d||(c?setTimeout(function(){a.hide(null)},500):k.storage.remove()),d=!0,"function"===typeof b&&b.call(a)};a.bindForm=function(b){if(b.add)k.event.add(b,"submit",function(b){b.preventDefault(b);b=b.target.elements;var c={},e,d,f,g;f=0;for(g=b.length;f<g;f++)if(e=b[f],d=k.util.getInputValue(e))c[e.name]=d;a.addToCart(c)});else if(b.display)k.event.add(b,"submit",function(b){b.preventDefault();a.show(b)});else return!1;
return!0};a.addToCart=function(b){var c=g.events,e=c.onAddToCart,c=c.afterAddToCart,d=!1,h=b;b={};var d={},l,m,r,p;for(l in h)f.test(l)?d[l]=h[l]:b[l]=h[l];l=0;for(m=a.products.length;l<m;l++)if(h=a.products[l].product,b.item_name===h.item_name&&b.item_number===h.item_number){r=!0;for(p=0;h["os"+p];){if(b["os"+p]!==h["os"+p]){r=!1;break}p++}if(r){b.offset=h.offset;break}}b.href=b.href||window.location.href;b.quantity=b.quantity||1;b.amount=b.amount||0;d["return"]&&-1===d["return"].indexOf("#")&&(d["return"]+=
"#"+g.name+"=reset");for(h=b.option_index?b.option_index:0;b["os"+h];){for(l=0;"undefined"!==typeof b["option_select"+l];){if(b["option_select"+l]===b["os"+h]){b.amount+=parseFloat(b["option_amount"+l]);break}l++}h++}b={product:b,settings:d};d=b.product.offset;if("function"!==typeof e||!1!==e.call(a,b.product))return(e=this.getProductAtOffset(d))?(e.product.quantity+=parseInt(b.product.quantity||1,10),e.setPrice(b.product.amount*e.product.quantity),e.setQuantity(e.product.quantity),d=!0):(b.product.offset=
a.products.length,d=v(b)),a.updateSubtotal(),a.show(null),k.storage.save(a.products,g.cartDuration),"function"===typeof c&&c.call(a,b),d};a.getProductAtOffset=function(a){return"undefined"!==typeof a&&this.products[a]};a.calculateSubtotal=function(){var b=0,c=a.products,e,d,f,g,h;h=0;for(g=c.length;h<g;h++)d=c[h],(e=d.product)&&e.quantity&&e.amount&&(f=e.amount,d=d.getDiscount(),b+=parseFloat(f*e.quantity-d));return b.toFixed(2)};a.updateSubtotal=function(b){var c=a.UI,e=c.cart.elements,d=c.subtotalAmount,
f=a.calculateSubtotal(),g=1,h,l,m,c="";if(e.currency_code)c=e.currency_code.value||e.currency_code;else for(m=0,l=e.length;m<l;m++)if("currency_code"===e[m].name){c=e[m].value||e[m];break}k.util.setText(d,k.util.formatCurrency(f,c));b||function y(){h=g.toString(16);g++;d.style.backgroundColor="#ff"+h;15<=g?(d.style.backgroundColor="transparent","0.00"===f&&a.reset()):setTimeout(y,30)}()};a.show=function(b){var e=parseInt(a.UI.cart.offsetTop,10),d=g.events,f=d.onShow,h=d.afterShow;b&&b.preventDefault&&
b.preventDefault();if("function"!==typeof f||!1!==f.call(a,b))k.util.animate(a.UI.cart,"top",{from:e,to:0},function(){"function"===typeof h&&h.call(a,b)}),a.UI.summary.style.backgroundPosition="-195px 2px",c=!0};a.hide=function(b,e){var d=a.UI,f=d.cart,d=d.summary,h=f.offsetHeight?f.offsetHeight:document.defaultView.getComputedStyle(f,"").getPropertyValue("height"),l=d.offsetHeight?d.offsetHeight:document.defaultView.getComputedStyle(d,"").getPropertyValue("height"),m=parseInt(f.offsetTop,10),r=g.events,
p=r.onHide,q=r.afterHide,h=e||0===a.products.length||!g.peekEnabled?-1*h:-1*(h-l-8);b&&b.preventDefault&&b.preventDefault();if("function"!==typeof p||!1!==p.call(a,b))k.util.animate(f,"top",{from:m,to:h},function(){"function"===typeof q&&q.call(a,b)}),d.style.backgroundPosition="-195px -32px",c=!1};a.toggle=function(b){c?a.hide(b):a.show(b)};a.reset=function(){var b=a.UI,d=g.events,e=d.onReset,d=d.afterReset;if("function"!==typeof e||!1!==e.call(a))a.products=[],c&&(k.util.setText(b.itemList,""),
k.util.setText(b.subtotalAmount,""),a.hide(null,!0)),k.storage.remove(),"function"===typeof d&&d.call(a)};return a}();var q=function(a,c){this._view(a,c)};q.prototype={_view:function(a,c){var d,e,f;this.product=a.product;this.settings=a.settings;this.liNode=document.createElement("li");this.nameNode=document.createElement("a");this.metaNode=document.createElement("span");this.discountNode=document.createElement("span");this.discountInput=document.createElement("input");this.priceNode=document.createElement("span");
this.quantityInput=document.createElement("input");this.removeInput=document.createElement("input");if(this.product&&(this.product.item_name||this.product.item_number)){this.product.item_name&&(d=this.product.item_name);k.util.setText(this.nameNode,d);this.nameNode.href=this.product.href;this.nameNode.appendChild(this.metaNode);this.product.item_number&&k.util.setText(this.metaNode,this.product.item_number,null,"<br>");d=this.getOptions();for(f in d)k.util.setText(this.metaNode,f+": "+d[f],this.metaNode.innerHTML,
"<br>");e=this.getDiscount();0<=e&&(this.discountInput.type="hidden",this.discountInput.name="discount_amount_"+c,this.discountInput.value=e,this.metaNode.appendChild(this.discountInput));this.getPrice();this.priceNode.className="price";d=this.getQuantity();this.quantityInput.name="quantity_"+c;this.quantityInput.className="quantity";this.quantityInput.setAttribute("autocomplete","off");this.setQuantity(d);this.removeInput.type="button";this.removeInput.className="remove";this.liNode.appendChild(this.nameNode);
this.liNode.appendChild(this.quantityInput);e&&this.liNode.appendChild(this.discountInput);this.liNode.appendChild(this.removeInput);this.liNode.appendChild(this.priceNode);for(f in this.product)"quantity"!==f&&-1===f.indexOf("discount_")&&(d=document.createElement("input"),d.type="hidden",d.name=f+"_"+c,d.value=this.product[f],this.liNode.appendChild(d))}else this.isPlaceholder=!0},getDiscount:function(){var a=0,c=this.getQuantity(),d=this.product.discount_num||c-1;0<=this.product.discount_amount?
(a=parseFloat(this.product.discount_amount),this.product.discount_amount2&&1<c&&(a+=Math.min(c-1,d)*parseFloat(this.product.discount_amount2))):0<=this.product.discount_rate&&(a=this.product.amount*parseFloat(this.product.discount_rate)/100,this.product.discount_rate2&&1<c&&(a+=Math.min(c-1,d)*this.product.amount*parseFloat(this.product.discount_rate2)/100));return a&&a.toFixed(2)},getOptions:function(){for(var a={},c=0;"undefined"!==typeof this.product["on"+c];)a[this.product["on"+c]]=this.product["os"+
c],c++;return a},setQuantity:function(a){var c;a=parseInt(a,10);this.product.quantity=a;this.quantityInput.value!==a&&(this.quantityInput.value=a,c=this.getDiscount())&&(this.discountInput.value=c,this.discountNode.innerHTML||this.metaNode.appendChild(this.discountNode),k.util.setText(this.discountNode,g.strings.discount+k.util.formatCurrency(c,this.settings.currency_code)));this.setPrice(this.product.amount*a)},getQuantity:function(){return void 0!==typeof this.product.quantity?this.product.quantity:
1},setPrice:function(a){a=parseFloat(a,10);k.util.setText(this.priceNode,k.util.formatCurrency(a.toFixed(2),this.settings.currency_code))},getPrice:function(){return(this.product.amount*this.getQuantity()).toFixed(2)}};var k={};k.storage=function(){var a=g.name;return window.localStorage?{load:function(){var c=localStorage.getItem(a),d,e;c&&(c=JSON.parse(decodeURIComponent(c)));if(c&&c.expires&&(d=new Date,e=new Date(c.expires),d>e)){k.storage.remove();return}return c&&c.value?c.value:c},save:function(c,
d){var e=new Date,f=[],g,h,k;if(c){k=0;for(h=c.length;k<h;k++)g=c[k],f.push({product:g.product,settings:g.settings});e.setTime(e.getTime()+864E5*d);e={value:f,expires:e.toGMTString()};localStorage.setItem(a,encodeURIComponent(JSON.stringify(e)))}},remove:function(){localStorage.removeItem(a)}}:{load:function(){var c=a+"=",d,e,f,g,h;try{for(e=document.cookie.split(";"),h=0;h<e.length;h++){for(f=e[h];" "===f.charAt(0);)f=f.substring(1,f.length);0===f.indexOf(c)&&(g=f.substring(c.length,f.length),d=
JSON.parse(decodeURIComponent(g)))}}catch(k){}return d},save:function(a,d){var e=new Date,f=[],k,h,m;if(a){m=0;for(h=a.length;m<h;m++)k=a[m],f.push({product:k.product,settings:k.settings});e.setTime(e.getTime()+864E5*d);document.cookie=g.name+"="+encodeURIComponent(JSON.stringify(f))+"; expires="+e.toGMTString()+"; path="+g.cookiePath}},remove:function(){this.save(null,-1)}}}();k.event=function(){var a=[];if(document.addEventListener)return{add:function(c,d,e,f){f=f||c;var g=function(a){e.call(f,
a)};c.addEventListener(d,g,!1);a.push([c,d,e,g])},remove:function(c,d,e){var f,g=a.length,h;for(h=0;h<g;h++)if(f=a[h],f[0]===c&&f[1]===d&&f[2]===e&&(f=f[3]))c.removeEventListener(d,f,!1),delete a[h]}};if(document.attachEvent)return{add:function(c,d,e,f){f=f||c;var g=function(){var a=window.event;a.target=a.target||a.srcElement;a.preventDefault=function(){a.returnValue=!1};e.call(f,a)};c.attachEvent("on"+d,g);a.push([c,d,e,g])},remove:function(c,d,e){var f,g=a.length,h;for(h=0;h<g;h++)if(f=a[h],f[0]===
c&&f[1]===d&&f[2]===e&&(f=f[3]))c.detachEvent("on"+d,f),delete a[h]}}}();k.util={animate:function(a,c,d,e){d=d||{};d.from=d.from||0;d.to=d.to||0;d.duration=d.duration||10;d.unit=/top|bottom|left|right|width|height/.test(c)?"px":"";var f=(d.to-d.from)/20,g=d.from;(function m(){a.style[c]=g+d.unit;g+=f;0<f&&g>d.to||0>f&&g<d.to||0===f?(a.style[c]=d.to+d.unit,"function"===typeof e&&e()):setTimeout(m,d.duration)})()},getInputValue:function(a){var c=a.tagName.toLowerCase();return"select"===c?a.options[a.selectedIndex].value:
"textarea"===c?a.innerText:"radio"===a.type?a.checked?a.value:null:"checkbox"===a.type?a.checked?a.value:null:a.value},setText:function(a,c,d,e){c=(d||"")+c.replace("<","&lt;").replace(">","&gt;");c+=e||"";a.innerHTML=c},formatCurrency:function(a,c){var d={AED:{before:"\u062c"},ANG:{before:"\u0192"},ARS:{before:"$"},AUD:{before:"$"},AWG:{before:"\u0192"},BBD:{before:"$"},BGN:{before:"\u043b\u0432"},BMD:{before:"$"},BND:{before:"$"},BRL:{before:"R$"},BSD:{before:"$"},CAD:{before:"$"},CHF:{before:""},
CLP:{before:"$"},CNY:{before:"\u00a5"},COP:{before:"$"},CRC:{before:"\u20a1"},CZK:{before:"Kc"},DKK:{before:"kr"},DOP:{before:"$"},EEK:{before:"kr"},EUR:{before:"\u20ac"},GBP:{before:"\u00a3"},GTQ:{before:"Q"},HKD:{before:"$"},HRK:{before:"kn"},HUF:{before:"Ft"},IDR:{before:"Rp"},ILS:{before:"\u20aa"},INR:{before:"Rs."},ISK:{before:"kr"},JMD:{before:"J$"},JPY:{before:"\u00a5"},KRW:{before:"\u20a9"},KYD:{before:"$"},LTL:{before:"Lt"},LVL:{before:"Ls"},MXN:{before:"$"},MYR:{before:"RM"},NOK:{before:"kr"},
NZD:{before:"$"},PEN:{before:"S/"},PHP:{before:"Php"},PLN:{before:"z"},QAR:{before:"\ufdfc"},RON:{before:"lei"},RUB:{before:"\u0440\u0443\u0431"},SAR:{before:"\ufdfc"},SEK:{before:"kr"},SGD:{before:"$"},THB:{before:"\u0e3f"},TRY:{before:"TL"},TTD:{before:"TT$"},TWD:{before:"NT$"},UAH:{before:"\u20b4"},USD:{before:"$"},UYU:{before:"$U"},VEF:{before:"Bs"},VND:{before:"\u20ab"},XCD:{before:"$"},ZAR:{before:"R"}}[c]||{};return(d.before||"")+a+(d.after||"")}}}})();
